name: tam-dask
channels:
  - https://www.idiap.ch/software/bob/conda/label/beta/
  - conda-forge
dependencies:
  - python==3.9
  - dask
  - dask-jobqueue
  - gridtk
  - bob.pipelines
  - bob.bio.face
  - scipy
  - jupyterlab
  - python-graphviz
  - graphviz
  - pandas
  - numpy 
  - scipy 
  - scikit-learn
